### ISSUE TITLE
도커를 활용하여 각 모델이 돌아가는 환경을 구성하고, 도커 간 통신 기능을 제작해주세요

### ISSUE THREAD

**Issue by 10wook** [AnBoIms/AnBoIms#208]

**Comment by iveib004** [comment]
현재 SRNet 연결을 제외한 mmdetection, craft의 API 연결은 완료한 상황입니다
docker-compose로 4개의 이미지 모두 container 안에서 잘 돌아가는 것을 확인했으니, model관련 코드 push해 주세요
파일 용량이 100MB를 넘는다면 Git LFS(Large File Storage) extension을 사용하여 올려주세요. 1TB 이상이 아닌 한 무료입니다
모델 코드를 넣고 각 모델별 app.py에 로직을 추가하여 이미지 안에서 돌아가는지 확인해주세요
