### ISSUE TITLE
간판 탐지 모델 학습

### ISSUE THREAD

**Issue by 10wook** [AnBoIms/AnBoIms#49]
간판탐지 성능을 확인해주고 만약 필요하다면 
기존의 한글 간판들 데이터를 활용해 학습시켜 성능향상을 시도해주세요

**Comment by 10wook** [comment]
학습이 다 되었다면 산출된 모델도 함께 업로드 해주세요

**Comment by 10wook** [comment]
모델 업로드 해주시고, 연결해서 완료로 해주세용

@iveib004 @WooJHo

**Comment by iveib004** [comment]
https://drive.google.com/drive/folders/1kw5wkx0sVWSvs8oW9W3Re-rncdfiUU6A?usp=drive_link
여기서 각각 sign 이랑 id_card로 각각 쭉 들어가시면 epoch 파일들 있는 폴더 나옵니다.
거기서 각자 에폭 24.pth를 받으시고 이름을 sign_epoch_24.pth, id_epoch_24.pth로 변경한 후 temustargram 레포에서 사진과 같이 work_dirs만드셔서 넣고 돌리시면 돌아갑니다
![image](https://github.com/user-attachments/assets/d9e052a5-11ad-49e7-baf5-08b574d2013f)
