### ISSUE TITLE
업스케일링

### ISSUE THREAD

**Issue by 10wook** [AnBoIms/AnBoIms#60]
업스케일링 코드를 확인해주시고, 몇 픽셀에서 몇픽셀까지 확대가 가능한지 확인해서 알려주세요

**Comment by 10wook** [comment]
@DDunos

**Comment by DDunos** [comment]
싫어요

**Comment by 10wook** [comment]
성능이 좋지 않은 이유로 최종적으로 업스케일링은 활용하지 않았습니다.
