### ISSUE TITLE
인페인팅

### ISSUE THREAD

**Issue by 10wook** [AnBoIms/AnBoIms#99]
GAN 기술에서 글씨를 마스킹 했을때 잘 작동하는지 확인하는 작업이 필요 합니다.

**Comment by 10wook** [comment]
현재 openCV로 구현이 가능함을 확인했으나, 활용에 대한 논의가 필요한 상황입니다

**Comment by iveib004** [comment]
인페인팅은 OpenCV로 구현할 예정이며, 이와 별도로 SRNet도 연결할 예정입니다
